"""empty message

Revision ID: 201574bc10f8
Revises: 
Create Date: 2020-06-22 18:32:49.555242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201574bc10f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shelf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sh_desc', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sh_desc')
    )
    op.create_table('books',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('b_title', sa.String(length=30), nullable=True),
    sa.Column('b_publisher', sa.String(length=30), nullable=True),
    sa.Column('b_shelf_id', sa.Integer(), nullable=True),
    sa.Column('b_quantity', sa.Integer(), nullable=True),
    sa.Column('b_language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['b_language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['b_shelf_id'], ['shelf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cds',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('c_title', sa.String(length=30), nullable=True),
    sa.Column('c_shelf_id', sa.Integer(), nullable=True),
    sa.Column('c_quantity', sa.Integer(), nullable=True),
    sa.Column('c_language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['c_language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['c_shelf_id'], ['shelf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dvds',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('d_title', sa.String(length=30), nullable=True),
    sa.Column('d_shelf_id', sa.Integer(), nullable=True),
    sa.Column('d_quantity', sa.Integer(), nullable=True),
    sa.Column('d_language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['d_language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['d_shelf_id'], ['shelf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dvds')
    op.drop_table('cds')
    op.drop_table('books')
    op.drop_table('shelf')
    op.drop_table('language')
    # ### end Alembic commands ###
